FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["Leetcode/Leetcode.csproj", "Leetcode/"]
RUN dotnet restore "Leetcode/Leetcode.csproj"
COPY . .
WORKDIR "/src/Leetcode"
RUN dotnet build "Leetcode.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Leetcode.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Leetcode.dll"]
